--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  creationTimestamp: ~
  labels: 
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: "{{ .Values.name }}"
  strategy: {}
  template: 
    metadata: 
      creationTimestamp: ~
      labels: 
        app: "{{ .Values.name }}"
    spec: 
     imagePullSecrets:
      - name: my-registry-key
      containers: 
        - 
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          imagePullPolicy: Always
          name: moviesiteapp-x86-6pdds
          resources: {}
status: {}

