apiVersion: v1
kind: Secret
metadata:
  name:  my-registry-key
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
        "ewoJImF1dGhzIjogewoJCSIxOC4xMTguOS43Mzo4MDgzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0
NllXUnRhVzR4TWpNPSIKCQl9LAoJCSIxOC4xODkuMTcwLjEwODo4MDgzIjogewoJCQkiYXV0aCI6
ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQl9LAoJCSIzLjEyLjc0LjIwNzo4MDgzIjogewoJCQki
YXV0aCI6ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQl9LAoJCSIzLjEzMy4xMTcuNjE6ODA4MyI6
IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZZV1J0YVc0eE1qTT0iCgkJfSwKCQkiMy4xNS4xNDQuMjA1
OjgwODMiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVdSdGFXNHhNak09IgoJCX0sCgkJIjUyLjE0
LjE5LjEyMjo4MDgzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQl9LAoJ
CSI2NTU4OTUzODQ4NDUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHsKCQkJImF1
dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsT01taHNZVVJLYVU0eFVtOWthM2hXV2xW
R1RscFlWakpaV0VwVllqQk9iMkZJUW5aWlZFSkRWa1pqZG1FeVZuVlRiWFF6VWtSU01Vc3ljRVZh
Ym1ob1RtMDVjbFI2YUU1VU1HTXhWMFJuTlZaNlJubE9hazVoWlVWd1RsSkdjRWRTYkdoSlVrYzFR
MkZzUm1Ga1JrNTBWRzFhVEZSR2JFVlRTRnBvWTBSYVFrOVZlRVJWYTJ4S1kyNUNObE51VmxGVWJF
cE1XVmN3ZDJWWFZtbGtSRW94VGxkc00yRlRkR0ZVV0VwT1dtdHdUMkpGTlhKVGF6QXdWMnBDV1U5
SWFGRmhNbVJGVWtVeGRGZEhWbXRVVlU1eVRteE9UR0o2YUhsak1FWXlWakk0ZW1WV1FuRlhiR3hh
Vm14VmRsSllRa2RSZWtad1RYbDBSVkpWY0ZSTlJYQkhVVEJhYVZwWVpGZGpNbXhWV1hrNVFsVnRU
ak5pYWtKdVpVWnNRa3d6UmxCVVZFSnVUVVZHZW1GV2FFUlJiWEJQWTNsMFJtTXlSbEpoVlRReFVU
SktRMVl3YkVwVFNGRjRXVE5zVTFveU9ESlViR2hzWkVkT2VtUllTa0prTVZaSlVsVk9TRlpUZEZs
aE1WcHNWMnhvVEZWdVRqTlVhMVl6V2xaT2FHTllUblZUUlRsWFkxVjRTMVI2UVROa2EyUkNWVzVL
UWxWSVFsRldNV1JSWlZac2JreDVPRFZsUkZwUVpFWldTMDVJWkZObFZWWjBZVU00ZG1KVVdrSk9S
elZaVWxaQk5WZFVWbnBrUm5CcVZucGFWRTR4Um5OaVZVcFBVMnRyZGxKVlkzSldWemxaWVcxT1Vr
MUdiRmxVTW14SlVXMUZkbVJYVWxsUFJFNTBUVlpDU0ZRelpHNVJNVTVIVFc1b1RWVkVXWHBUTWta
WlZtMVdkRlpWU2tkVE1IQTBVVzV3ZDFkdVpIVlRWekZMVVZaTk1HTnNRblJhUkVaMlVqSm5jbE50
VVROUmFsSTFXVlJTV1dOVmVGaFNSbVF6VFZaUk5VNXVaRkJYVld4S1lWaEtXRnBIUmtSTk1uQk9W
MWhTV1dKRVFscFJibkJDWTI1Uk5WbFhkRTFpYTNjMVZrTTRNbVZFVmpOa2EzUXpWbFZHVDAxc1Ft
aFRTRXBZWTFWU1NGcElSbHBVTVdRMFlXMTBUbFZyUlRCaFF6a3pWbXhHY21NelFucE5SRTQyVm0x
ek1WWnRNWGhrVmtaaFUyNUJOVlV6YUdsbFNGRnlWMFZzTVdKV1NrTk5NMFo2VkdwYWFFOVhVa1Jo
YkZVeVZFaGpkMWt5TlhCa2JFWkdWbnBvTkZNd1RqVmhWRlZ5VVZWWmVFMXRPWEprYlRVd1ZVWlNh
VlV6V2tSbGJYUnBZekE0TVUweU5VMVNNamg0VG10T1JGWkdRa2RqYlRWRFlrWldObUpJVVhoYWJW
cHpZbGhXVmsxV1JrdGFiWEJGWTJ4T1lWRXdhR3BWU0d4TllXNUNiV0ZXYkVWVGJWRXhTekJHTVdG
VVFsbGpSMUp6VjBWSk5VMXJXa1JQVnpWNVlrVmFUVnBGVW1GWFZYaHRUMGhPTVZKclNuQmhWR3hO
VmtkV2FsSnRPREppVlc5NlpERk9iMVZJWkdGTk1XUk9ZakpvVkZVd2RFWlhSVnBWVFcxb1RsSlVS
VEJoZWs1Q1RYcFNVVXN6VWtWT1ZURmFWRVV4UjJJd1NuWldSRnBYV201b05sb3lhR3RUU0ZWNFVr
aHNWRlpWZUZobFNFNXdUVE5hVTFVd01IWlJWMDVZVmpORk1HSkdUbE5UYkVKV1dsUldjbEpVYkZC
VlJUQjZVakJvUmxaNlVrcFpWVXBXVTBScmVsVnRaREJhV0ZaR1lUSktSbGt4V214VU1sSlJZVlpL
YldKWE9IaGhWVTUyV1RJNGVFMUdWbTFrTVZwNlQxUmtTV1ZyV1RWa1IwNHlWbXRzZVdWc1FubFdh
elZxV1ZSR1RGSnNjSHBrVm5CNldXdG9jVTB5YnpWTmEydzBUbE4wWVZJd05IbFhSV3cyVkVoa2Rs
b3hVbmRqVkd4RFZsVTVlbGxZUWtaU2VsVXlUV3BPYVZRd1JuVlRhbWd5WWpCd2RHTnJNVTlTV0U0
d1UwVktTazVIV1RGbGJGcHJVbGhLYmt0NWRHNU5ibFp4VWxoamVVNHhUa3BNTWprelRrUktTVmRy
ZURWVU1uaE1UVWRWTUZsV1drdFJNazVhVTBSQ1lXSlljRWRaTW1neFZsVndVR05XVmtoVFZUQnlU
MFpzTWxkVlZsQlRha2wyV20xRmNsVXpXa3BOUlU1NFUzcEtObE5VVGtsaE1VNXpXVEJXU1ZkRVNq
VlZNSE15VFZaS1ExSkZTblpoZVhSMFV6Rm9jbGt5VlhsTlJUa3pZbXBhZG1KWFRtaGxXR2hoWkZa
T2RtUkhNWEJTZVhSc1ZYcE9kMk5yVmtWVFZ6bFdZa2hOTUZJeGFETlRSV3hVVFRKamRscEdhRWRa
TWxwdVVGUXdhVXhEU210WldGSm9ZVEpXTlVscWIybFJWa1pHVVd0R1NXRklaSFJOUm14b1UxWk9T
MXBXU2pCVGJUQXhZbXBHU0U1dVZuaGFWMVp5VjBoV2RsZEdhRkZhVkZaV1VtMU9iRTlXU25oUFF6
aDRUa2hrUWxGVlJrbE9TR1J0VVZac1MxTXlPV0ZUVjJneVdUQTFRbFZYVGtoaU1HTTBaREpLVWxO
VlNrSlNSVXAyVVcxa2NtTlhhSEpoVldNMVpIcENRMUZ1WkVaa01HaHVWMVZ3V2xOV2NFcFJWbVJX
VWtWS1FsSllWazVSYTFaR1VrVldOVkl3Tlc5T1dFSklWVlV4VFZsVWFFbFRTRnBDVTFWS1JsTlZS
VE5UTW1oUlZqQndVVTVWYkc1UFJXZDZXVmhuY2tzd09WaGtia1YzWWpKc1QxZHFXa1pYYWtwQ1ls
UmplVk5zU25wVU1scE9WSGwwZDJKR2J6RlhSRkpRVVROd01XTXlSWGhrYTBaTlZXcGFObHBVVm5w
VGF6VllWbTAxU1ZreVJYSlNWRkpJWkdzMVJrMUVNR2xNUTBveVdsaEtlbUZYT1hWSmFtOXBUV2xK
YzBsdVVqVmpSMVZwVDJsS1JWRldVa0pZTUhSR1YxTkpjMGx0VmpSalIyeDVXVmhTY0dJeU5HbFBh
a1V5VFdwUmQwOVVUWGhPYWxJNSIKCQl9LAoJCSI2NTU4OTUzODQ4NDUuZGtyLmVjci51cy1lYXN0
LTIuYW1hem9uYXdzLmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxx
YjJsVVZVNVlVVEZ2Y21SdWJ6VmhXRm8xVlVWc00xa3pSa1JsV0U1TFlrVTFNbEZ0TlZkVE1rcFJU
VVJXVWt0NU9WUk9SMUV4VkROa2IwOVhaSEpXUjNSMFlqTmFNRmt5Wkd4TU1HTXlaRVpPYjJGclVs
TlVWbEZ5VjFjMVdVNVhSa3hWYmtvd1pWWktlbE5xYkVWVVZtaDFVVEkxU2xSVk5VUmxiV041VTBo
d1NsUnFSbGhXYTJSRVZrUk9SbUV4U25SWGJuQlhUMVZzZDJKc1VtRlNSVWwyVlhwU2FscERkRmxN
TTJ4UVQxWnNTRTVZUm5GTk1XdzJVakZ3U1U0eWJ6VlpWMUp4Vm01dmVGVnFWakJVYTNCWFZWVjBO
bUZIUm1GVWJXOHdZVVZzTUZsVk1UVmpWa0pMVkRCU1NVNHlkRVJPUjFKNVRXcENNbGRXVlRGTWVr
bDZVbXBDUms0eFRrdFNNVkl4WlZad2MyUnFTa2RPUlVwYVpVaGFkRXN4VG0xbFdIQlRaRlJHUmxG
WGNGVmlXSEJ5WkZVNWNGWXdOWHBSTURsRFdWZG5kMWRGV21wVFYxRjRVMjVzTTFGcVFYSlNha2x5
WlcwNVFtRlZSWGhPVjFaNFYyNWFjR05WZDNwUFIwcDJaREZDTUdSc2FIbE9Na1poV2pKNE5HSlZN
VmxsYVhSMlpVWldTVmxVVms5T2EyTXdZV3hHVkZkdFVqWk9WR2gyWTFVMWJHVlhWbWhsVjJzd1lr
TTRNbFZ1VmpaVmVYUkZUWGwwVjJGdFdYWlJiVlkyWVhwQ00xZFdSWFpPYkZwRFZETkNObFJyYkRO
YU1FcHhUVEJLY2xsNlFrUlVWR3Q0VTFSTk5XTnJhM3BTZVRsRVlsZHNVVTVFUWxaU2JXeFBUMWhT
ZEZWRVdtbGhNakUyVXpGU2FHTXhaRzFrVjBseVVteHJjbHA2VlhaVlYyUnVZa1ZuZUdSRldrOVpN
WEIyVERCc2JHSlZPVmhoYTFKRlUxaGtObFJIZURWamJGSjRUa1JhTUZORVpGQlZhbU41V1d0b1RH
SnNVbk5oUjA1dlVUTktNMlZGZDNwaU1uUlVZVmhWZGxJeGJIQk9SWGg2WkZkNFMxWnFUa05hTWxa
T1lVWmpOV015VmtKUmJFNVNVakZzYTA5Rk5ETmpNSGQyVVdwTmRscHJXVE5XVlhoTVZGWk9NV0ZG
V25Sa2F6RklVakZyTTFKc1VsVlZiR1JRV1cxWk1GUnRSa1pXYXpGTFRqTkdSMDlZU2pKWGFscFla
RlJCTWxKdVZqWmlNRlpDVmpCYVFtVnJaR2hsVkZKTFZHdEpNMDlIVW1wT01qQTBVVlUxVEZKNlpH
bFVNV2hKVGtoa2RWZEZaRVJVTTBFMVpWVjNlazFxUlhwamJIQXlWbmwwY1UxVE9EQlZhbFpFVFVV
MU1HVkZSa3RhTUZKdVN6QktUbFI2UWtST1ZWSnJZVlZuZGxaV1dtRmxSRWt3VlVaR1ZFc3lPVmhP
TVUxMlRXMDFSRTVVVWt0VWFsWlVZV3BzVUdWcVRuZGtiRUo2VW10cmNtUnFiR3hVUlhoWFZrZDRO
bEl3ZURWUFZGVXhWRlZXV1ZsNmJHeGpTRXBOVjBWa2NVNTZhREprUm5CTVRtNWtUMUZXVWtaT01V
Wk9UWHBaZWsxdVduaGtSVGxMV20xU1MyUXlUbTFVVm1zeVZtNVJkbUpVU25WUFdGSTFVak5HYkV3
d1dUQlRhMUl4VVROV01XUlVaRXhoYWtwWlpVZEdRMVZWV2xwYWJURm9aRWhDYWxOWVRURmlWRkp6
WW1zeGIwOUhiSEZWYVRsTllXeGFVRlJGY0VOVmExVXlZekE1VldKVWJFcGtWR3hOVW5sMFYwOVZh
R3hXVldodFVrVldTVmRzYUZKVWFtUjJWa2RKTlZNd1p6VmhSVEUwVDBoU05GZFVWblJTYmxVeldr
aHJNRlJXUm5aaWJURlVXVEIzTldKRlZYbFVNWEJxVlRKYVRXUnJlRTVTTW1jeFZqTnNkbUZ0WkhW
aE1scFZUVEphVVdFd2RIZE9SMHBvWkcxV1NWWkhkR3BMTTBVMFVUQmtSRTR3T1UxVE1tUk9WMWMx
TlZOSGNIbFRWR1JvV21wR2FtSlhiM2xVVkdkMlN6SnJNRk14Um1oV1JFSjZaVWRzYVZRd05WUmxW
V3hFWld0b2RFd3hUbXhOUjFadVN6Sm9jMWRGTlhkU1IwWnVaVVJzY21KR1RYcE5ibVJyVW01RmQx
WnNSbEpqVjJkNFZGaFJNRkZyYXpWaE0wWnpZVVZ3UWxReWVIcGtSelZXWlc1cmQxcFlVazFSVldS
MldXcGFWbFl3YkhKak1qazJVVmRhU2xsNldtdGhWR3hPV2pCT1dGWlZOSGhVYld0MlUwUmFiV0V6
Y0RWT01HZzBXbGMxYlZScmNHNU9lWFJVVlVSb01sVnJVbmRrYXpWMFpGUkdkV1JWWkRaU01XOHlU
VzEwTldGWVJsbFRNalZFVFRCMFMyUkZOREZUTUhodVVGUXdhVXhEU210WldGSm9ZVEpXTlVscWIy
bFJWa1pHVVd0R1NXRnJTVE5NTW14dVpEQXhiazVGTlZGa01rWXhZMjVvVkZOV2JEUk9SV2h0WW01
b01WSXlUWFpPUkdocFVraGtNbVF3VW5kVWJHeFlWMjFrUWxGVlJrbE9TR1J0VVZac1MxTXlPV0ZU
VjJneVdUQTFRbFZYVGtoaU1HTTBaREpLVWxOVlNrSlNSVXAyVVcxa2NtTlhhSEpoVldNMVpIcENR
MUZ1WkVaa01HaHVWMVZ3V2xOV2NFcFJWbVJXVWtWS1FsSllWazVSYTFaR1VrVkdSR1ZIV21GYWJF
SkpUVVpTYmsxSFl6UlVWelZDVTFWS1JsTlZSVE5QUTNSRVRrUk9kVmR0Y3pWYVZ6VTFXbGhPUm1S
R1dsVldiSEJFVkRGSmVGcHNUbkJWV0dSRFlXeGtOVXN5V21wYWJXeHpZMVJLVDFaVVJtbGtNblJE
VVc1YVNscFZlSGxoU0djeVlURlpNMVJXV1RKa1ZURjZWRVJyZWxwSGFISlpWVFZzVlROV1JWUlVN
R2xNUTBveVdsaEtlbUZYT1hWSmFtOXBUV2xKYzBsdVVqVmpSMVZwVDJsS1JWRldVa0pZTUhSR1Yx
TkpjMGx0VmpSalIyeDVXVmhTY0dJeU5HbFBha1V5VFdwVmVVMVVZek5OVkVvNSIKCQl9LAoJCSJl
YzItMTgtMTE4LTktNzMudXMtZWFzdC0yLmNvbXB1dGUuYW1hem9uYXdzLmNvbTo4MDgzIjogewoJ
CQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQl9LAoJCSJlYzItMy0yMy0xMDMtMjQy
LnVzLWVhc3QtMi5jb21wdXRlLmFtYXpvbmF3cy5jb206ODA4MyI6IHsKCQkJImF1dGgiOiAiWVdS
dGFXNDZZV1J0YVc0eE1qTT0iCgkJfSwKCQkiZWMyLTUyLTE0LTE5LTEyMi51cy1lYXN0LTIuY29t
cHV0ZS5hbWF6b25hd3MuY29tOjgwODMiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2WVdSdGFXNHhN
ak09IgoJCX0sCgkJImVjMi01Mi0xNC05OC0xMDcudXMtZWFzdC0yLmNvbXB1dGUuYW1hem9uYXdz
LmNvbTo4MDgzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NllXUnRhVzR4TWpNPSIKCQl9Cgl9Cn0="
