apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: moviesite-app
  name: moviesite-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: moviesite-app
  type: LoadBalancer
status:
  loadBalancer: {}
